services:
  apache:
    #build:
    #  context: ./apache
    image: lauheit/apache:latest
    container_name: apache
    networks:
      - app-network

  nginx:
    #build:
    #  context: ./nginx
    #container_name: nginx
    image: lauheit/nginx:latest
    ports:
      - "80:80"
      - "443:443"
    depends_on:
      - apache
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
